### ISSUE TITLE
Connection refused when running docker command

### ISSUE THREAD

**Issue by ralyodio** [forkdelta/backend-replacement#100]
`docker-compose run contract_observer alembic upgrade head`

Connection refused
	Is the server running on host "postgres" (172.18.0.3) and accepting
	TCP/IP connections on port 5432?

I'm on a mac, do I need to run a database outside of docker?

**Comment by freeatnet** [comment]
@chovy No, you definitely do not need to run a DB outside of the containers. When you do `docker-compose run contract_observer …`, the postgres container should be started automatically. If it does not start successfully, you might want to do `docker-compose up postgres` in a separate terminal tab and check the log output.

**Comment by M-Zeeshan-Haider** [comment]
when i run `compose run contract_observer` or `docker-compose up postgres` i get this error, please help me

![Screenshot from 2019-06-27 16-40-45](https://user-images.githubusercontent.com/36418814/60263555-5eb9ed80-98fa-11e9-9c53-28569243b17b.png)
###
