### ISSUE TITLE
Don't get any orders or trades events from websocket api

### ISSUE THREAD

**Issue by shavive** [forkdelta/backend-replacement#103]
I am connecting to the websocket api at: wss://api.forkdelta.com/socket.io/?transport=websocket and I can use the getMarket call without problems. However I don't get any orders or trades events. I use the same code with the link switched to the etherdelta websocket and I am able to get orders (haven't looked at trades yet) without any problems. Are there any known issues regarding this? I am using python 3.5 on Win7, websocket package version 0.48. Also, the forkdelta socket doesn't seem to remain connected very long despite pings every 10 seconds. So my getMarket calls stall frequently which I then need to resend after reconnecting. Any known bugs with these characteristics? TIA.

**Comment by pointtoken** [comment]
I get trade events but no order events...
