### ISSUE TITLE
Server configuration Issue

### ISSUE THREAD

**Issue by nknk1410** [forkdelta/backend-replacement#106]
I am getting such error on server configuration for forkdelta Backend Replacement. any help will be very appreciated

Error Message: 
  conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "root"
 (Background on this error at: http://sqlalche.me/e/e3q8)

Thanks

**Comment by analyzedmediadeepak** [comment]
Hi 
You can update alembic.ini  file  line no 38 
sqlalchemy.url = postgresql+psycopg2://username:password@localhost:5432/dbname

**Comment by freeatnet** [comment]
I'm sorry, I do not have the bandwidth to provide support for individual configuration issues.
