### ISSUE TITLE
Parity node isn't responding correctly.

### ISSUE THREAD

**Issue by shrinivasmani** [forkdelta/backend-replacement#117]
Hi Admin
 
Parity node isn't responding correctly. Check that HTTP_PROVIDER_URL points to a Parity Ethereum node's HTTP interface (default port 8545) and that WS_PROVIDER_URL points to the WebSocket interface (default port 8546).
Ref: ( https://github.com/forkdelta/backend-replacement/issues/109 )
 
So, I have created Parity node etherium config.toml file from here https://paritytech.github.io/parity-config-generator/
and uploaded that file on server but still getting Errors
 
When we run Command: docker-compose run contract_observer alembic upgrade head then getting Errors like:
 
[root@centos-s-1vcpu-2gb-blr1-03 backend-replacement]# docker-compose run contract_observer alembic upgrade head
Starting backendreplacement_postgres_1 ...
Starting backendreplacement_redis_1 ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
 
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
 (Background on this error at: http://sqlalche.me/e/e3q8)

 ===================================================================
When we run command:  docker-compose logs -f
 
Then getting Errors:  https://pastebin.com/MeUrBRJ5

**Comment by freeatnet** [comment]
I'm sorry, I do not have the bandwidth to provide support for individual configuration issues.
