### ISSUE TITLE
IP Banned

### ISSUE THREAD

**Issue by abrahamchaibi** [forkdelta/backend-replacement#134]
Hello! I think my IP address has been getting banned by the forkdelta api server. Could you help me sort out what I am doing wrong? It is frustrating as I keep having to change IP's and feels rather like I am not solving the root issue. (Also not sure where to file support tickets so figured I would start here).

**Comment by freeatnet** [comment]
Blocked IPs are flushed periodically. If you are caught by anti-abuse systems, you will be blocked, and you will have to wait until you're unblocked.
