### ISSUE TITLE
WebSocket connection error 301

### ISSUE THREAD

**Issue by shrinivasmani** [forkdelta/backend-replacement#136]
Hi
I am getting the error mention bellow

WebSocket connection to 'wss://api.etokenmarket.com/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 301

![websocket](https://user-images.githubusercontent.com/34855216/50555720-21cbc000-0cf6-11e9-82db-91f14a69070e.png)

Thanks for any help will be greatly appreciated

**Comment by freeatnet** [comment]
Closing as stale. Please reopen if you still need help with this.
