### ISSUE TITLE
Is API hopelessly broken or what?

### ISSUE THREAD

**Issue by CrackerHax** [forkdelta/backend-replacement#209]
When I emit for a specific token I get a returnTicker for all tokens... According to the documentation I should be getting a returnTicker for the token I specified. 

Also, according to the docs I am only supposed to get order lists when I add a user address, but I am getting order lists for the token I specified and they are all extremely outdated, out of order or just plain wrong but I can tell it's the order book for the token because some orders are correct.

Either the docs are outdated (or just very poorly written) or API is broken.

**Comment by CrackerHax** [comment]
Looking at the backend code it appears the documentation is wrong. When you emit for a token you get the trades and order lists, nothing else. Even so... the data in these lists appears to be all wrong/outdated/out of order. 

Were the docs written before coding (i.e. 'this is how its going to be when it's done') or were they written for older code that used to behave according to the documentation?

How about emitting current returnTicker for the specified token? Isn't that sort of expected behavior in an exchange api? I figure if I emit "market" { token="0x8a854288a5976036a725879164ca3e91d30c6a1b",  user=""} I should get an ETH_0x8a85428 returnTicker object back.

I would do it myself but I just don't have time (or extra resources) to set up a full test server. Seems like an easy fix for someone who has already done this.

**Comment by freeatnet** [comment]
I don't have time to fix based on a drive-by issue.

**Comment by CrackerHax** [comment]
Seems you don't want your time wasted but everybody else's is wasted trying to get your bad implementation to work. I looked at the issues list and it's not just me. At least fix your documentation please.
