### ISSUE TITLE
Add ticker to the API

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/backend-replacement#3]

**Comment by JonathonDunford** [comment]
Similar to returnTicker data.

We need to figure out what all should be included with our basic call.

Should full orderbook be included so that developers don't have to keep calling separate tokens for order book?

Needs to pull this data from the database.

I vote that the base call includes the full orderbook and full ticker data.

**Comment by freeatnet** [comment]
@JonathonDunford I think we'd need to measure how much data is a full orderbook. It's probably quite a bit, given that we have ~80k orders simultaneously open across ~700 tokens, while users will only need a few in a single session.

P.S. I know why you want the full orderbook, but I'd say developers should be encouraged to set up an own instance of the API and source data from that without any rate limits.

**Comment by JonathonDunford** [comment]
Agreed. We need to determine the viability of it.

However, it would be nice to dump the orderbook in one transaction.

**Comment by JonathonDunford** [comment]
I started working on this as can be seen on the "returnTicker" branch.

It seems like we should have another database table with the ticker/token information to make this process easier so we don't have to search through a huge order database every time this is called.

The table could be updated with the observers.

@freeatnet

**Comment by freeatnet** [comment]
Agreed. If we want to implement incremental updates (ticker updates event-by-event), I think we should write up the logic of it before diving in.

**Comment by JonathonDunford** [comment]
More comments and code here: https://github.com/forkdelta/backend-replacement/pull/18
