### ISSUE TITLE
connecting to socket.io api

### ISSUE THREAD

**Issue by MichaelRazum** [forkdelta/backend-replacement#34]
Hello,

as I understand you also provided your own socket.io API. Is this correct? Is there a way to connect to it? 

The default APIs in etherdelta where 
https://socket01.etherdelta.com, https://socket02.etherdelta.com,...

I tried the API under 
http://api.forkdelta.com

but it doesn't work.

Thanks for any help or hint.

**Comment by freeatnet** [comment]
Hey @MichaelRazum. Keen eye on the hostname! We require HTTPS, however, so the correct API URL is https://api.forkdelta.com.

Please note that this is currently not being offered as a public API. We reserve the right to change the API at any time, so use it at your own risk.

**Comment by MichaelRazum** [comment]
Yes I tried https as well. A bit strange but getting errors using socket.io javascript client.
Here is my code: For n = 0 (forkdelta) it doesn't work.  For the other sockets, everything is fine, except that the order book isn't complete.

```
const io =require('socket.io-client')
const n = 0
const sockets = ["https://api.forkdelta.com",
                 "https://socket02.etherdelta.com",
                 "https://socket03.etherdelta.com",
                 "https://socket04.etherdelta.com",
                 "https://socket05.etherdelta.com",
                 "https://socket06.etherdelta.com"]


const socket = io.connect(sockets[n], {
  transports: ['websocket'],
  reconnection: true,
  reconnectionDelay: 1000,
  reconnectionDelayMax: 5000,
  reconnectionAttempts: 99999
});
```

**Comment by freeatnet** [comment]
Please post the error.

**Comment by MichaelRazum** [comment]
It simply doesn't connect. 
It doesnt triggers the 'connect' function:

`socket.on('connect', () => {
  console.log(' socket connected ');
  console.log("connecting to socket " + sockets[n])
  send_socket_message();
  request_market_data()
});`

 Instead jumps to 

`socket.on('reconnect_attempt', () => {
  console.log(try reconnect")
  socket.io.opts.transports = ['websocket'];
});`

Thanks for trying to help!

**Comment by freeatnet** [comment]
Try subscribing to `error` or `connect_error` events, they might provide useful error messages.

**Comment by MichaelRazum** [comment]
Thanks! Seems tho be a certificate issue. Any idea how to solve this? 
![image](https://user-images.githubusercontent.com/6819881/36261248-0a5da56a-1264-11e8-855f-f1b296844c67.png)

**Comment by MichaelRazum** [comment]
OK got a solution. Have to add "rejectUnauthorized: false" in the configuration of the socket client! Thanks a lot for helping!

**Comment by freeatnet** [comment]
We use LetsEncrypt for API certs. Check that your system has up-to-date CA package, including LetsEncrypt Authority cert.

You should be able to also hit https://api.forkdelta.com/ from a browser to see if this is a system-wide issue or if perhaps there's a separate CA library in your code's environment. 

**Do not** use `rejectUnauthorized: false` if you need to trust data you receive.

**Comment by MichaelRazum** [comment]
Actually going with the browser works fine. Seems to be an issue with the socket.io client or some configuration issue. If I find out more I will post here! 
 
For me the solution is fine. Since I just want to get the order book. The messages are signed so its possible to check if they are valid.

**Comment by ateene** [comment]
I'm also can't connect to the forkdelta socket.io api. I get "404: Not Found" when I try accessing https://api.forkdelta.com/ from a chrome browser.

**Comment by mrbianchi** [comment]
what data provides wss://socket01.etherdelta.com/socket.io/?EIO=3&transport=websocket ?
