### ISSUE TITLE
Too many decimals in API responses

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/backend-replacement#35]
**Expected:** A reasonable number of decimal places for float values.
**Observed:** Utter madness.

```
{
	"id": "0x97b79f47473e6b68516c984ab2de4054ef2582adf38aa366d1513b6b6c21714b_sell",
	"user": "0xc73604d0514ac01e63513d07601e7e98f2f117b4",
	"tokenGet": "0x0000000000000000000000000000000000000000",
	"amountGet": "2.00e+22",
	"tokenGive": "0xd4fa1460f537bb9085d22c7bccb5dd450ef28e3a",
	"amountGive": "1e+8",
	"expires": "5105269",
	"nonce": "733997509",
	"availableVolume": "1e+8",
	"ethAvailableVolume": "1.0000000000000000209225608301284726753266340892878361046314239501953125",
	"availableVolumeBase": "2.00e+22",
	"ethAvailableVolumeBase": "20000.000000000001430848481092438490170561123698464954523412728804032667540013790130615234375000",
	"amount": "1e+8",
	"amountFilled": "0",
	"price": "20000.0000000000010123972644898690154820850913677594522122677091193265910041380238173236084484497591809775743356864299612716916438423333750459851098292956622954777595992929496691428126238194672813683532392374144035467070912806853187505836593308656649117339275453367627182356519758479869264882765100097939088468490866440732567026286411800662521663033681010552508571602373973818562449257340260893973314436215128040640055868046470247375279548919891031850819054271812657289404126706255227332385821622424600036494436073624343655131356375408455509268762930691074648079535591348465941827953843168799252633246515511329153578515946477076280086918871265500802154000695035803744390622509509152272872747162202879306602826433708708864386296342016781915006233269144242547418444636985819315622636613317554893304766030455675377145578696160938459071457157497996611529670987242607269394306887656927999719503442150242780904615620395498249284070611317741330679831977446847311950267971019201433059016368447734522802894731",
	"state": "OPEN",
	"v": 28,
	"r": "0x74700930e094e3efbd176aef20c65304604c4d98ecd7c1bfbc1dbe5c33887b45",
	"s": "0x691d5518c84443081ecad18d4782f0eede32a53babf35df2411aeb001f82986f",
	"date": "2018-02-15T15:05:08.275767",
	"updated": "2018-02-15T15:05:08.275767"
}
```

**Comment by mmhh1910** [comment]
This no longer seems to be the case.

However, I scientific notation is used a lot. Not sure if we are loosing precision here, but anyhow, I would prefer int values like "100000000" instead of "1e+8".

**Comment by mmhh1910** [comment]
I have a branch where I feed in forkdelta orders from the FD websocket API like it is done in production for ED orders from the ED API.

This shows that we emit orders that are not accepted by our own standards.

E.g.:

`forkdelta_observer_1   | forkdelta_observer WARNING  FD Order rejected: Invalid message format: {'data': {'id': '0x2848870854bc273a90b43b3114395c0bae03c1433ac9a9235267b12b3f40c817_sell', 'user': '0xf32d616182f0ed57d845d0f9cf8db2d3829c79ec', 'state': 'OPEN', 'tokenGet': '0x0000000000000000000000000000000000000000', 'amountGet': '9.5000e+16', 'tokenGive': '0x327682779bab2bf4d1337e8974ab9de8275a7ca8', 'amountGive': '1e+20', 'expires': '5157689', 'nonce': '1.12363e+9', 'v': 27, 'r': '0x154b2f33f8d5b58647c070be9f0c6f5465cf85740dab010640d7b29f1c956451', 's': '0x1f58901627acc9a5cc66fd3e889576e0a44fb33722c0f8b67add25d1172b5009', 'date': '2018-02-14T19:56:27.416884', 'updated': '2018-02-22T17:25:34', 'availableVolume': '3.066443421e+11', 'ethAvailableVolume': '3.066443421e-7', 'availableVolumeBase': '291312125', 'ethAvailableVolumeBase': '2.913121250e-10', 'amount': '3.066443421e+11', 'amountFilled': '0', 'price': '0.00095'}, 'errors': {'nonce': ["field 'nonce' cannot be coerced: invalid literal for int() with base 10: '1.12363e+9'", 'must be of integer type']}}
`

Same happens with expires field.

=> We should generally not emit ints in scientific notation.

`forkdelta_observer_1   | forkdelta_observer WARNING  FD Order rejected: Invalid message format: {'data': {'id': '0xa223fa30c8a272cc14d4bc1165f345762ef7addc04eed5511ab2b09737863f4d_buy', 'user': '0xe964115135319875c5a431a6e24df2c5986d6bfb', 'state': 'OPEN', 'tokenGet': '0x1bb9e8ea817d56eccc212ce63f7da95298f98719', 'amountGet': '1.0e+9', 'tokenGive': '0x0000000000000000000000000000000000000000', 'amountGive': '0', 'expires': '5142301', 'nonce': '3388406454', 'v': 28, 'r': '0xcf6954b39d9c7fd0e5a233b365a86b6426cb9d9fb1fac8268c4ca25ec8611cce', 's': '0x6ba1b60cfe8f3361a52a9e1a55af229c33bbe73173ac4c6f52cea8d654c8ab89', 'date': '2018-02-21T21:00:29.956238', 'updated': '2018-02-21T21:00:29.956238', 'availableVolume': '1.0e+9', 'ethAvailableVolume': '10000000.00', 'availableVolumeBase': '0', 'ethAvailableVolumeBase': '0', 'amount': '-1.0e+9', 'amountFilled': '0', 'price': '0e+2'}, 'errors': {'amountGive': ['min value is 1']}}`

We no longer accept "amountGet/Give == 0", but there are still orders like this in the prod DB. Should we clean this up?

**Comment by freeatnet** [comment]
This has been fixed.
