### ISSUE TITLE
Filter out stale orders with the availableVolume contract call

### ISSUE THREAD

**Issue by triamazikamno** [forkdelta/backend-replacement#36]
https://etherscan.io/address/0x8d12a197cb00d4747a1fe03395095ce2a5cc6819#code
function on the line 289
You can use it to check if the order still has volume or was traded already.

**Comment by freeatnet** [comment]
Doing that already ;)
https://github.com/forkdelta/backend-replacement/blob/master/app/tasks/update_order.py#L87

**Comment by triamazikamno** [comment]
Stale orders are still shown in the orderbook though. Maybe you are updating the number, but not deleting the order when it has no volume?

**Comment by freeatnet** [comment]
A few orders have accumulated where a miniscule volume is still available. We'll work to filter those out.

**Comment by freeatnet** [comment]
@triamazikamno Thank you for bringing it up though, I appreciate you taking the time to make this suggestion!
