### ISSUE TITLE
placeing orders: invalid signature

### ISSUE THREAD

**Issue by MichaelRazum** [forkdelta/backend-replacement#41]
Hello,

I think that might be an Issue but not 100% sure. When placing orders I'm getting sometimes the error: 
[422,"Cannot post order: invalid signature"]

Here is one example: this one is fine
`{"nonce": 1169671266, "contractAddr": "0x8d12A197cB00D4747a1fe03395095ce2A5CC6819", "s": "0x5f74de64efee8725cdaaf68373bc4e40c7e6755519bdb122d026e4866da4c6b8", "v": 27, "user": "0xaA8d1EE37F6b18f754A55f1d5f18B4C88af2AaCc", "amountGive": 2000000000000000000, "r": "0xb55837fa1b04baa90f48b9cb3a819715a16fe2a405c456cc10d7ce766e602ddb", "tokenGive": "0xE41d2489571d322189246DaFA5ebDe1F4699F498", "tokenGet": "0x0000000000000000000000000000000000000000", "amountGet": 3975975974000000, "expires": 5109254}`

Here s the second order. Created with the same method. Here I get the error 402
`{"nonce": 6426437636, "contractAddr": "0x8d12A197cB00D4747a1fe03395095ce2A5CC6819", "s": "0x5e713c0fa7265f91d5c56f3f485ff72a1985cae2eabcdc4b55f6624fe5dac2c8", "v": 28, "user": "0xaA8d1EE37F6b18f754A55f1d5f18B4C88af2AaCc", "amountGive": 2000000000000000, "r": "0x37a60b1533c9c6e0aae04b39c7732425e7ffe8eafddbc38d25cfde38d3781ae7", "tokenGive": "0x0000000000000000000000000000000000000000", "tokenGet": "0xE41d2489571d322189246DaFA5ebDe1F4699F498", "amountGet": 1546790409899458500, "expires": 5109256}`

What I did so far: check that the hex method I am using before signing the message is correct. It gives exactly the values as make_order_hash in this project. After that the message is signed using 
`self.account.sign(message_hexstr=hashhex)` (web3 v4.0.0-b.9)

Any Idea what that could be? Maybe an error in the order_signature_valid "black magic" ritual?

**Comment by MichaelRazum** [comment]
Please close the issue. I think I know what is going on and the "black magic" should work. Had a problem with javascript big numbers and python2socket.io interface...

**Comment by marcoalkema** [comment]
I am actually having this same issue and can't figure out how to create a proper signature.
Now, I've been using some code that was used in a trading bot for EtherDelta, so I'm not sure how valid that still is.

Could someone please provide an example of how to create a valid signature? Do I have to pack/condense the arguments (`contractAddr, tokenGet, amountGet, tokenGive, amountGive, expires, nonce`) first?
