### ISSUE TITLE
Incorrect ticker data

### ISSUE THREAD

**Issue by JonathonDunford** [forkdelta/backend-replacement#46]
I spy a bug.
Ticker data shows bid as 5000 ETH / 1 KIN for this: https://forkdelta.github.io/#!/trade/KIN-ETH

That happened, but it was traded yesterday and there have been plenty of trades since.

**Comment by JonathonDunford** [comment]
Need to filter out low ETH volume orders in returnTicker when are scanning the orderbook.

**Comment by perich** [comment]
Since we hardcoded `FILTER_ORDERS_UNDER_ETH = 0.001`, we should add a reminder to circle back to this in ~6 months or a year in case ETHUSD has increased enough to warrant changing this value

**Comment by JonathonDunford** [comment]
@grahamperich It will need to be increased to 0.01 soon.
We want to add the option for people to pass in the ETH filter through the API instead of hard coding it in the API.
