### ISSUE TITLE
ropsten testnet error

### ISSUE THREAD

**Issue by northeastsquare** [forkdelta/backend-replacement#69]
In main ethereum net, main.json works well. 
But when I test backend on testnet ropsten, I do the following:
1. in https://github.com/forkdelta/forkdelta.github.io  change testnet.json to main.json
2. app/config.py in backend-replacement: 
       FRONTEND_CONFIG_FILE="./app/testnet.json" 
      ED_CONTRACT_ADDR = '0x228344536a03C0910Fb8Be9C2755c1a0bA6f89E1
after that, I got the following error in chrome console, spending long time on it but  with no success:   
wss://192.168.12.16:8080/socket.io/?EIO=3&transport=websocket' failed: WebSocket opening handshake timed out WS.doOpen @ main.js:33881 

  While websocket server return:    
HTTP/1.0 400 Bad Request
Content-Type: text/html; charset=utf-8
Content-Length: 11
Date: Tue, 06 Mar 2018 01:09:24 GMT
Server: Python/3.6 aiohttp/2.3.7

**Comment by northeastsquare** [comment]
OK , change client side config/main.json:
"socketServer": ["http://192.168.12.16:8080"]
https --> http

**Comment by AlbertChanX** [comment]
Did u make a order in test net?  the orders received on the front end are from this `api` (wss://socket01.etherdelta.com/socket.io/?EIO=3&transport=websocket) ???  but this orders are from mainnet, so is there a accomplishment of order api?
