### ISSUE TITLE
Not seeing events 'orders' and 'trades'

### ISSUE THREAD

**Issue by Ferb2011** [forkdelta/backend-replacement#73]
When connected to the websocket api, I can request market data but do not see new orders and trades being emitted.

**Comment by mmhh1910** [comment]
Can you post your request and the response you get?

**Comment by Ferb2011** [comment]
I'm simply testing using:
```
socket.on('orders', () => {
	console.log('new order')
});

socket.on('trades', () => {
	console.log('new trade')
});
```

It seems 'orders' works now, but 'trades' does not.

**Comment by freeatnet** [comment]
@Ferb2011 Do I understand correctly that you never see `trades` events at all, for any tokens?

**Comment by Ferb2011** [comment]
Yes thats correct
