### ISSUE TITLE
Possible issue with backend

### ISSUE THREAD

**Issue by Palm0live** [forkdelta/backend-replacement#77]
I have had a problem with a filled order not showing up in the trades section. Neither the personal trades section, nor the "public" one to the right of the screen. 

Token MWAT: Order of 5750 tokens filled @0.000063 but not removed from order book and not showing in the trades section. 

This leads me to believe that there is an issue with the backend.

Looking also at token Zilliqa, there are traded orders on the book that are not showing in the trades section. I believe this might be the same thing happening, as happened to my own personal order.

Zilliqa order:
![image](https://user-images.githubusercontent.com/37428853/37501602-6680062c-28cf-11e8-99a8-5fb55ad1afe7.png)
Cannot be traded, but no sign of the order in the trades section:
![image](https://user-images.githubusercontent.com/37428853/37501628-88acdb26-28cf-11e8-9db7-d8e0343ad940.png)

**Comment by nihalmpatel** [comment]
I have the same issue. Have you found any solution?
