### ISSUE TITLE
Is it possible to add orders to a testnet backend

### ISSUE THREAD

**Issue by georgek146** [forkdelta/backend-replacement#78]
I have a dapp that needs to use forkdelta, i'm wondering if it's possible to get the api set up to accept test orders so that i can make sure my system fully works before testing with real tokens.

**Comment by mmhh1910** [comment]
Does your dapp  need a backend server or does it only communicate with the chain?

**Comment by georgek146** [comment]
my dapp needs to take orders, and because no one can place orders to the order book when they are connected to kovan, i cannot do testing. so my dapp needs to talk to both your backend server and the chain.

**Comment by mmhh1910** [comment]
I've asked because the ED contract also lets you add orders on chain. You could do this with the ED contract that you deployed to kovan.

I'm in the process of creating a truffle setup for the FD smart contract with js test cases that creates orders this way that might help.
