### ISSUE TITLE
Keep track of availableVolume of an Order

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/backend-replacement#8]
This is a follow-up on #1.

In #1, I added tracking of `orderFills`, which allowed us to get the unfilled amount of the order. However, the amount remaining may be unfillable if the market maker withdraws funding for the order. We need to track that and temporarily remove the order from the returned orderbook.

**Comment by freeatnet** [comment]
`availableVolume` changes when:
1. The order is partially or completely filled.
2. The market maker deposits or withdraws funds backing the order (`tokenGive` of the order).

**Comment by JonathonDunford** [comment]
Currently contract_observer has all of the data necessary for this.

We will need contract_observer to add these events to some sort of queue for a worker to process and the worker will adjust "availableVolume" on affected orders.

Orders can be affected on trade/withdraw/deposit/cancel.
