### ISSUE TITLE
API stops sending orders, trades and funds events 

### ISSUE THREAD

**Issue by dmf7z** [forkdelta/backend-replacement#80]
Every two or three days, ForkDelta API stops sending API events: orders, trades and funds as defined in https://github.com/forkdelta/backend-replacement/tree/master/docs/api#events.

This causes frontend or any other app using the API to have an outdated orderbook.

The only solution seems to be to restart the websocket server.

All other functionality of the API keeps working fine. Calls to message and getMarket work ok.

Here is a preview of the frontend working ok and receiving events.

![fd events](https://user-images.githubusercontent.com/770590/37750116-0e1aff88-2d6a-11e8-98d8-fa94115627bc.png)

When API starts failing, all those events are not received.

**Comment by githubsolution** [comment]
I Want To Create API Return Ticker For My Exchange For Receive Live Data For Listing On CoinMarketCap Help Me Thanks You
