### ISSUE TITLE
Cannot create order: Invalid signature

### ISSUE THREAD

**Issue by marcoalkema** [forkdelta/backend-replacement#84]
I've been struggling to find out how to create an order. Mostly I get stuck on the actual signing.
I'm currently trying out some code I found in the EtherDelta bot examples and functions I find in Web3 or Eth-utils.

I was wondering if someone could help me and provide me with a quick example on how to sign and create an order.

Thank you in advance :)

**Comment by freeatnet** [comment]
Hey @marcoalkema! https://github.com/forkdelta/backend-replacement/blob/master/app/src/order_signature.py#L6 should give you an idea of the order signing structure. Let me know if you need more info!

**Comment by marcoalkema** [comment]
Hey @freeatnet, thank you very much for your reply! 

It has clarified some, mostly that the Web3 library I'm using is not supporting a few of the functions you're using... I forgot to mention that I'm using Javascript to do this. 
Even simple functions like toInt are not supported in the JS version of the Web3 library.

You don't happen to have a working example in Javascript, do you? :D

**Comment by freeatnet** [comment]
https://github.com/etherdelta/bots/blob/master/js/service.js#L340 looks quite messy, but should work out of the box.

**Comment by marcoalkema** [comment]
Great! Got it working for the most part. I'm not yet able to get my orders to cancel, but I'm sure I'll get there! Thanks a lot!
