### ISSUE TITLE
Slow/non-existent response to getMarket requests

### ISSUE THREAD

**Issue by Ferb2011** [forkdelta/backend-replacement#86]
To initiate orderbooks for a bunch of token addresses in config.addresses, I run:

```
_.each(config.addresses, function(address){
                    setTimeout(book_request, 2000, address)
                    
     })
function book_request(address){
        socket.emit('getMarket', { token: address, user: "" })
    }
```

And to get updates, I run:

```
socket.on('market', (market) => {
       //do stuff
       setTimeout(book_request, 5000, market.orders.buys[0]['tokenGet'])
}
```

However I get a maximum of 4 or 5 markets on initial requests, and updates never arrive. Prior to this week it worked much faster, even without setting timeouts

(Updated by @freeatnet for formatting)

**Comment by freeatnet** [comment]
At a glance, you might benefit from listening to `orders` events to receive orderbook updates. `getMarket` event is really meant for initial data loading and may be optimized for that purpose in the future.

In terms of the specific situation, can you provide your IP address or some of the socket.io sids you've received?

**Comment by Ferb2011** [comment]
Thanks for checking, are orders that are not new but should be updated because they've been fully/partially traded or cancelled als emitted in the 'orders' event?

**Comment by freeatnet** [comment]
Indeed [they are](https://github.com/forkdelta/backend-replacement/tree/master/docs/api#orders)!
