### ISSUE TITLE
How can I connect to backend server? 

### ISSUE THREAD

**Issue by Edison767e** [forkdelta/backend-replacement#89]
Hi All,

I followed the instruction to run the backend systems, it was running smoothly in the terminal.  then I cloned the forkdelta.github.io(forkdelta frontend) and tried to change the socketServer in config/main.js to "http://localhost/". 

but when I visited forkdelta frontend in my localhost  it shows "WebSocket connection to 'ws://localhost/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 404" in console. What's the correct way to connect the backend system with front-end UI? 

Thanks

Edi

**Comment by i-am-vivek** [comment]
Either You need to install the forkdelta backend in local, or you need to configure forkdelta websocket server in your local code. you can configure it in config/main.json.
