### ISSUE TITLE
Installation issues 

### ISSUE THREAD

**Issue by gochainwallet** [forkdelta/backend-replacement#93]
Hello I have been trying this for a few days now and Im still not getting anywhere please can someone assist me.
Im trying to install backend-replacement
ubuntu 18.04 

when I run development mode I can see the api on api.domain.com:8080 
but when I run production mode im not getting a responce on https://api.domain.com

**Comment by freeatnet** [comment]
@gochainwallet You'll need to provide more details than that. What are your steps? What do you expect? What actually happens?

**Comment by gochainwallet** [comment]
Thank you @freeatnet 
Sorry for the latereply I have made instructions to every step I have done 
https://pastebin.com/1Z7wvutE

also I have out put the errors
https://pastebin.com/G29qaCzm

when I run it in development mode if I browse to api.domain.com:8080 I can see not found and it works 
when I run it in production mode I was expecting https://api.domain.com but I cant seem to find it 

do I need to install certbot and manually configure nginx with the certs and a reverse proxy for https://api.domain.com   ? or is the script ment to do it for me

**Comment by analyzedmediadeepak** [comment]
What is the use of HTTP_PROVIDER_URL ,WS_PROVIDER_URL and  is their need to configure this IP and port no from server end

HTTP_PROVIDER_URL=http://138.197.160.134:8545/
WS_PROVIDER_URL=ws://138.197.160.134:8546/

Reference: https://github.com/forkdelta/backend-replacement/blob/master/default.env
