### ISSUE TITLE
Please can someone assist me with this error

### ISSUE THREAD

**Issue by gochainwallet** [forkdelta/backend-replacement#94]
Hello everybody

I have been trying this for arround a week now
when I start docker I get a few errors but then they go a way for a while and it looks fine 
on the website I can see it is connected to the api and the ticker is running but I dont see any graph and orders dont work 

this seems to be the error
etherdelta_observer_1  | IndexError: list index out of range

here is the out put from running docker and my eth node
https://pastebin.com/Bdsyd8bG

What is the best command to start the eth node 
 --ws --rpc --rpcaddr .................

Also if someone is willing to help me set it up I can pay for the trouble

Thank you

**Comment by nihalmpatel** [comment]
I'm also facing the same problem. What's the solution?
