### ISSUE TITLE
Configuration Issue with Sockets

### ISSUE THREAD

**Issue by AdamSC1-ddg** [forkdelta/backend-replacement#97]
@freeatnet - Hoping you can help!

I've been trying to fork my own forkdelta + backend to run fully independently of the current infrastructure (except for the contract), to reduce centralized dependencies.

I've managed to get everything working except for the sockets to update the charts on the UI of the exchange.

My configuration is two servers:

-DomainA which hosts the front-end UI and the backend within an Apache configuration.

-DomainB which hosts a parity node within an Nginx configuration.

When I run `docker-compose up` to bring up the backend, I receive the notice from `websocket_server_1` that says "======== Running on http://0.0.0.0:8080 ========"

So in the forkdelta front end "Main.json" file I've set my socket server to DomainA.com (which is also the URL of the front-end UI)and in `config.py` I've updated the "ED_WS_SERVERS" to "wss://DomainA.com/socket.io/?EI0=3&transport=websocket"

Yet, when navigating to the site, I get a perpetual loading symbol for the order book and trade history along with the console error:

`WebSocket connection to 'wss://DomainA.com/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 404`

I also get a 404 when attempting to navigate to DomainA.com/returnTicker.

Is there additional routing configuration that needs to be done at the webserver level to support the websockets and API? Or am I missing a component of the configuration?

**Comment by freeatnet** [comment]
I'm sorry, I do not have the bandwidth to provide support for individual configuration issues.

**Comment by icinsight** [comment]
This is an extremely relevant question and there is zero documentation on these options anywhere. Thumbs down.
